[package]
name = "rusterizer"
version = "0.1.0"
authors = ["michel <michel.strelow97@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
rayon = "1.0.3"
rocket = "0.4.0"
rocket_contrib = "0.4.0"
time = "0.2.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
